defmodule AshSqlite.TransactingRepo.Migrations.AddTransactingRepo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transacting_posts, primary_key: false) do
      add :subtitle, :text
      add :title, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:transacting_posts)
  end
end