defmodule AshSqlite.TestRepo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify :decimal, :decimal, default: nil
      modify :type, :text, default: nil
      modify :category, :citext
    end

    alter table(:post_links) do
      modify :state, :text, default: nil
    end
  end

  def down do
    alter table(:post_links) do
      modify :state, :text, default: "active"
    end

    alter table(:posts) do
      modify :category, :ci_string
      modify :type, :text, default: "sponsored"
      modify :decimal, :decimal, default: "0"
    end
  end
end