defmodule AshSqlite.TestRepo.Migrations.TestCodegen do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:devices, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :entity, :map, null: false
      add :name, :text, null: false
      add :id, :text, null: false, primary_key: true
    end

    create unique_index(:devices, [:id], name: "devices_unique_id_index")
  end

  def down do
    drop_if_exists unique_index(:devices, [:id], name: "devices_unique_id_index")

    drop table(:devices)
  end
end