defmodule AshSqlite.TestRepo.Migrations.AddDeviceStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:devices) do
      add :status, :text, null: false
    end
  end

  def down do
    alter table(:devices) do
      remove :status
    end
  end
end